### PR TITLE
Update with newer data source plus friendlier Python 3 codes 

### PR DESCRIPTION
**Pull request by hanteng**
Update with newer data source plus friendlier Python 3 codes.

Country.csv is also added to provide basic mapping of country codes and names.

### CODE REVIEW

**Comment by rgrp** [comment]
@hanteng you still have the bad commits in there ;-) e.g.

https://github.com/hanteng/imf-weo/commit/5453033e19059a9f4cb6787b1e6962464c9af790

Did you try the reclone the imf-weo repo clean and then copying over changes (not pulling but literally copying)?

**Comment by hanteng** [comment]
Not sure if I understand you. Currently I only see four files have been
changed:

https://github.com/datasets/imf-weo/compare/master...hanteng:master

As for the example you have given me, it was just one of the intermediate
steps.

I did try reclone the imf-weo several times, and then copying over the
changes.  If you are looking to remove the editing history, I am not sure
how I can do that.Can you bear with me and let me know how?



2015-09-19 7:43 GMT+08:00 Rufus Pollock <notifications@github.com>:

**Comment by rgrp** [comment]
@hanteng that's because the compare won't show the files changed in the original commit because you fixed them later. Just look at the commits listed here esp the first one - you can see that it includes the stuff added at the start.

You need to "crush" the commits or do what i suggest which is reclone the "clean" repo and *copy* (not pull) across the file changes.

**Comment by hanteng** [comment]
Just to clarify, is it "One Commit per Pull Request" you are suggesting now
as described here?
http://ndlib.github.io/practices/one-commit-per-pull-request/  Please do
let me know it is.

2015-09-21 20:02 GMT+08:00 Rufus Pollock <notifications@github.com>:

**Comment by rgrp** [comment]
What i'm saying is this current pull request still includes your initial commits where you push data in wrong location. You then later remove that in a subsequent commit (see the list of commits above in this PR). Thus when you do a simple comparison you don't see the commits but they are there. I'd prefer a clean pull request without the initial "error". There are several ways to do this in git - you can "squash" commits, you can clone the repo clean and just copy over the changed files from your current repo, commit and then do a PR etc.

**Comment by hanteng** [comment]
Will it do? https://github.com/datasets/imf-weo/pull/6

2015-09-22 18:54 GMT+08:00 Rufus Pollock <notifications@github.com>:

**Pull request closed without merging**
